// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/medications/data/models/medicine_object_box_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7768628635660357013),
    name: 'MedicineObjectBoxModel',
    lastPropertyId: const obx_int.IdUid(24, 816540448144724395),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4220230178406858809),
        name: 'objectBoxID',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7877846591538032837),
        name: 'id',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7406869334810307877),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4281897016612523578),
        name: 'dosage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 64806723711354131),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4948589142224755999),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4079466097281231093),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1420540025662427916),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6230799157140055628),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8213018171037882677),
        name: 'doseTimesStrings',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 9074415681171311096),
        name: 'frequency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5814219871142235366),
        name: 'selectedWeeklyDaysInts',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8686114294138418875),
        name: 'customInterval',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 7768628635660357013),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      2710202074535320957,
      5298320495002613861,
      1775938178309142691,
      5361399253308868405,
      526134687370118618,
      6982978109404435744,
      667232479875923207,
      6385127576627302336,
      3576073966702581452,
      3866135810803336202,
      816540448144724395,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MedicineObjectBoxModel: obx_int.EntityDefinition<MedicineObjectBoxModel>(
      model: _entities[0],
      toOneRelations: (MedicineObjectBoxModel object) => [],
      toManyRelations: (MedicineObjectBoxModel object) => {},
      getId: (MedicineObjectBoxModel object) => object.objectBoxID,
      setId: (MedicineObjectBoxModel object, int id) {
        object.objectBoxID = id;
      },
      objectToFB: (MedicineObjectBoxModel object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        final dosageOffset = fbb.writeString(object.dosage);
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        final statusOffset = fbb.writeString(object.status);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final doseTimesStringsOffset = fbb.writeList(
          object.doseTimesStrings.map(fbb.writeString).toList(growable: false),
        );
        final frequencyOffset = fbb.writeString(object.frequency);
        final selectedWeeklyDaysIntsOffset = fbb.writeListInt64(
          object.selectedWeeklyDaysInts,
        );
        fbb.startTable(25);
        fbb.addInt64(0, object.objectBoxID);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, dosageOffset);
        fbb.addInt64(4, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(5, object.endDate?.millisecondsSinceEpoch);
        fbb.addOffset(6, typeOffset);
        fbb.addOffset(7, statusOffset);
        fbb.addOffset(8, notesOffset);
        fbb.addOffset(9, doseTimesStringsOffset);
        fbb.addOffset(10, frequencyOffset);
        fbb.addOffset(11, selectedWeeklyDaysIntsOffset);
        fbb.addInt64(12, object.customInterval);
        fbb.finish(fbb.endTable());
        return object.objectBoxID;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final objectBoxIDParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dosageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final startDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final endDateParam = endDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endDateValue);
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final doseTimesStringsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 22, []);
        final frequencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final selectedWeeklyDaysIntsParam = const fb.ListReader<int>(
          fb.Int64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 26, []);
        final customIntervalParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final object = MedicineObjectBoxModel(
          objectBoxID: objectBoxIDParam,
          id: idParam,
          name: nameParam,
          dosage: dosageParam,
          startDate: startDateParam,
          endDate: endDateParam,
          type: typeParam,
          status: statusParam,
          notes: notesParam,
          doseTimesStrings: doseTimesStringsParam,
          frequency: frequencyParam,
          selectedWeeklyDaysInts: selectedWeeklyDaysIntsParam,
          customInterval: customIntervalParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MedicineObjectBoxModel] entity fields to define ObjectBox queries.
class MedicineObjectBoxModel_ {
  /// See [MedicineObjectBoxModel.objectBoxID].
  static final objectBoxID = obx.QueryIntegerProperty<MedicineObjectBoxModel>(
    _entities[0].properties[0],
  );

  /// See [MedicineObjectBoxModel.id].
  static final id = obx.QueryStringProperty<MedicineObjectBoxModel>(
    _entities[0].properties[1],
  );

  /// See [MedicineObjectBoxModel.name].
  static final name = obx.QueryStringProperty<MedicineObjectBoxModel>(
    _entities[0].properties[2],
  );

  /// See [MedicineObjectBoxModel.dosage].
  static final dosage = obx.QueryStringProperty<MedicineObjectBoxModel>(
    _entities[0].properties[3],
  );

  /// See [MedicineObjectBoxModel.startDate].
  static final startDate = obx.QueryDateProperty<MedicineObjectBoxModel>(
    _entities[0].properties[4],
  );

  /// See [MedicineObjectBoxModel.endDate].
  static final endDate = obx.QueryDateProperty<MedicineObjectBoxModel>(
    _entities[0].properties[5],
  );

  /// See [MedicineObjectBoxModel.type].
  static final type = obx.QueryStringProperty<MedicineObjectBoxModel>(
    _entities[0].properties[6],
  );

  /// See [MedicineObjectBoxModel.status].
  static final status = obx.QueryStringProperty<MedicineObjectBoxModel>(
    _entities[0].properties[7],
  );

  /// See [MedicineObjectBoxModel.notes].
  static final notes = obx.QueryStringProperty<MedicineObjectBoxModel>(
    _entities[0].properties[8],
  );

  /// See [MedicineObjectBoxModel.doseTimesStrings].
  static final doseTimesStrings =
      obx.QueryStringVectorProperty<MedicineObjectBoxModel>(
        _entities[0].properties[9],
      );

  /// See [MedicineObjectBoxModel.frequency].
  static final frequency = obx.QueryStringProperty<MedicineObjectBoxModel>(
    _entities[0].properties[10],
  );

  /// See [MedicineObjectBoxModel.selectedWeeklyDaysInts].
  static final selectedWeeklyDaysInts =
      obx.QueryIntegerVectorProperty<MedicineObjectBoxModel>(
        _entities[0].properties[11],
      );

  /// See [MedicineObjectBoxModel.customInterval].
  static final customInterval =
      obx.QueryIntegerProperty<MedicineObjectBoxModel>(
        _entities[0].properties[12],
      );
}
