// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/medications/data/models/medicine_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8291714512488286130),
    name: 'MedicineEntity',
    lastPropertyId: const obx_int.IdUid(5, 2277127078062080438),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2972913938570541984),
        name: 'objectBoxID',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5503882446672202598),
        name: 'apiId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1068312268792641598),
        name: 'userEmail',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3056262963093514980),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2277127078062080438),
        name: 'encryptedData',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 8291714512488286130),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [7768628635660357013],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      2710202074535320957,
      5298320495002613861,
      1775938178309142691,
      5361399253308868405,
      526134687370118618,
      6982978109404435744,
      667232479875923207,
      6385127576627302336,
      3576073966702581452,
      3866135810803336202,
      816540448144724395,
      4220230178406858809,
      7877846591538032837,
      7406869334810307877,
      4281897016612523578,
      64806723711354131,
      4948589142224755999,
      4079466097281231093,
      1420540025662427916,
      6230799157140055628,
      8213018171037882677,
      9074415681171311096,
      5814219871142235366,
      8686114294138418875,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MedicineEntity: obx_int.EntityDefinition<MedicineEntity>(
      model: _entities[0],
      toOneRelations: (MedicineEntity object) => [],
      toManyRelations: (MedicineEntity object) => {},
      getId: (MedicineEntity object) => object.objectBoxID,
      setId: (MedicineEntity object, int id) {
        object.objectBoxID = id;
      },
      objectToFB: (MedicineEntity object, fb.Builder fbb) {
        final apiIdOffset = fbb.writeString(object.apiId);
        final userEmailOffset = fbb.writeString(object.userEmail);
        final statusOffset = fbb.writeString(object.status);
        final encryptedDataOffset = fbb.writeString(object.encryptedData);
        fbb.startTable(6);
        fbb.addInt64(0, object.objectBoxID);
        fbb.addOffset(1, apiIdOffset);
        fbb.addOffset(2, userEmailOffset);
        fbb.addOffset(3, statusOffset);
        fbb.addOffset(4, encryptedDataOffset);
        fbb.finish(fbb.endTable());
        return object.objectBoxID;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final objectBoxIDParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final apiIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userEmailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final encryptedDataParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = MedicineEntity(
          objectBoxID: objectBoxIDParam,
          apiId: apiIdParam,
          userEmail: userEmailParam,
          status: statusParam,
          encryptedData: encryptedDataParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MedicineEntity] entity fields to define ObjectBox queries.
class MedicineEntity_ {
  /// See [MedicineEntity.objectBoxID].
  static final objectBoxID = obx.QueryIntegerProperty<MedicineEntity>(
    _entities[0].properties[0],
  );

  /// See [MedicineEntity.apiId].
  static final apiId = obx.QueryStringProperty<MedicineEntity>(
    _entities[0].properties[1],
  );

  /// See [MedicineEntity.userEmail].
  static final userEmail = obx.QueryStringProperty<MedicineEntity>(
    _entities[0].properties[2],
  );

  /// See [MedicineEntity.status].
  static final status = obx.QueryStringProperty<MedicineEntity>(
    _entities[0].properties[3],
  );

  /// See [MedicineEntity.encryptedData].
  static final encryptedData = obx.QueryStringProperty<MedicineEntity>(
    _entities[0].properties[4],
  );
}
